SUBJECT_DATA = {
    "physics": {
        "mcq": [
            ["If the sizes of charged bodies are very small compared to the distances between them, we treat them as ____________.\n", "Zero charges\nPoint charges\nSingle charge\nNo charges"],
            ["The force per unit charge is known as ____________.\n", "Electric current\nElectric potential\nElectric field\nElectric space"],
            ["State true or false: The total charge of the isolated system is NOT conserved.\n", "True\nFalse"],
            ["What is the dielectric constant of a metal?\n", "-1\n0\n1\nInfinite"],
            ["The quantisation of charge indicates that -\n", "Charge, which is a fraction of charge on an electron, is not possible\nA charge cannot be destroyed\nCharge exists on particles\nThere exists a minimum permissible charge on a particles"],
            ["The property which differentiates two kinds of charges is called ____________.\n", "Equality of charge\nPolarity of charge\nFraction of charge\nNone of the option"],
            ["_______ gives the information on field strength, direction, and nature of the charge.\n", "Electric current\nElectric flux\nElectric field\nElectric potential"],
            ["What is the nature of gaussian surface involved in Gaussâ€™s law of electrostatics?\n", "Scalar\nElectrical\nMagnetic\nVector"],
            ["Which of the following statements is / are incorrect regarding the point charge?\n", "The charge Q on a body is always given by q=ne, where n is any integer, positive or negative.\nBy convention, the charge on an electron is taken to be negative.\nThe fact that electric charge is always an integral multiple of e is termed as quantisation of charge\nThe quantisation of charge was experimentally demonstrated by Newton in 1912."],
            ["Electric field at a point varies as r degree for\n", "Point charge\nDipole\nLine charge\nInfinite plane sheet of charge"],
            ["Two spheres have their surface charge densities in the ratio of 2:3 and their radii 3:2. The ratio of the charges on them is:\n", "3:2\n4:2\n2:3\n2:4"],
            ["Charge on a body is Q1 and it is used to charge another body by induction. Charge on second body found to be Q2 after charging, then\n", "q1 / q2 = 1\nq1 / q2 <1\nq1 / q2 â‰¤1\nq1 / q2 â‰¥1"],
            ["The force between 2 charges 0.0 6m apart is 5 N. If each charge is moved towards each other by 0.04 m then the force between them will become\n", "7.20 N\n11.25 N\n22.50 N\n45.00 N"],
            ["When a glass rod is rubbed with silk, it\n", "gains electrons from silk.\ngives electrons to silk.\ngains protons from silk.\ngives protons to silk."],
            ["The force between two charges is 120N. If the distance between the two charges is doubled, the force will be\n", "30N\n60N\n15N\n40N"],
            ["Two large metal sheets having surface charge density +Ïƒ and â€“Ïƒ are kept parallel to each other at a small separation distance d. The electric field at any point in the region between the plates is\n", "Ïƒ/Îµ0\nÏƒ/2Îµ0\n2Ïƒ/Îµ0\nÏƒ/4Îµ0"],
            ["When an electric dipole is placed in a uniform electric field, it experiences\n", "Force as well as torque\nTorque but no net force\nForce but no torque\nNeither any force nor any torque"],
            ["The angle between area of equipotential surface and electric field is-\n", "0 degree\n90 degree\nBetween 0degree and 90degree\nBetween 90degree and 180degree"],
            ["Three capacitors of capacitances 3ÂµF, 9ÂµF and 18 ÂµF are connected once in series and then in parallel. The ratio of equivalent capacitances Cs/Cp will be:\n", "1:15\n15:1\n1:1\n1:3"],
            ["The electric potential V at any point O (x, y, z all in metres) in space is given by V = 4xÂ² volt. The electric field at the point (1 m, 0, 2 m) in volt/metre is\n", "8 along negative x-axis\n8 along positive x-axis\n16 along negative x-axis\n16 along positive z-axis"],
            ["Which of the following options is correct? In a region of constant potential\n", "the electric field is uniform.\nThe electric field is zero.\nThere can be charge inside the region.\nThe electric field shall necessarily change if a charge is placed outside the region."],
            ["In a parallel plate capacitor, the capacity increases if\n", "area of the plate is decreased.\nDistance between the plates increases.\nArea of the plate is increased.\nDielectric constantly decreases."],
            ["If a unit positive charge is taken from one point to another over an equipotential surface, then\n", "work is done on the charge.\nwork is done by the charge.\nwork done is constant.\nno work is done"],
            ["Twenty-seven drops of mercury are charged simultaneously to the same potential of 10 volts. Whatwill be potential if all the charged drops are made to combine to form one large drop ?\n", "180 V\n90 V\n120 V\n45 V"],
            ["A capacitor has some dielectric between its plates, and the capacitor is connected to a dc source. The battery is now disconnected and then the dielectric is removed, then\n", "capacitance will increase\nenergy stored will decrease\nelectric field will increase\nvoltage will decrease"],
            ["Which of the following is blocked by a capacitor?\n", "A.C\nD.C\nBoth A.C. and D.C\nNeither A.C. nor D.C"],
            ["A dielectric is placed in between the two parallel plates of a capacitor as shown in the figure. The dielectric constant of the dielectric being K. If the initial capacity is C, then the new capacity will be:\n", "(K + l).C\nK.C\n((K+1)/2).C\n(k â€“ l)C"],
            ["A positively charged particle is released from rest in a uniform electric field. The electric potential energy of the charge\n", "remains constant because the electric field is uniform.\nincreases because charge moves along the electric field.\ndecreases because charge moves along the electric field.\ndecreases because charge moves opposite to the electric field."],
            ["Electric potential of earth istaken to be zero because earth is a good\n", "Insulator\nConductor\nSemiconductor\nDielectric"],
            ["A hollow metal sphere of radius 5 cm is charged so that the potential on its surface is 10 V. The potential at the centre of the sphere is\n", "0 V\n10 V\nSame as at point 5 cm away from the surface\nSame as at point 25 cm away from the surface"],
            ["The electrostatic force between the metal plates of an isolated parallel plate capacitor C having a charge Q and area A, is\n", "proportional to the square root of the distance between the plates\nLinearly proportional to the distance between the plates\nIndependent of the distance between the plates\nInversely proportional to the distance between the plates"],
            ["A capacitor is charged by a battery. The battery is removed and another identical uncharged capacitor is connected in parallel. The total electrostatic energy of resulting system\n", "increases by a factor of 4\nDecreases by a factor of 2\nRemains the same\nIncreases by a factor of 2"],
            ["The filament of 60W and 100 W bulbs are of same length. Then:\n", "60W filament is thicker\n100W filament is thicker\nboth are of same thickness\nboth cannot have same length"],
            ["Kirchhoffâ€™s first law (âˆ‘i=o) and second law(âˆ‘iR=âˆ‘E),where the symbols have their usual meanings, are respectively based on:\n", "Conservation of charge, conservation of momentum\nConservation of energy, conservation of charge\nConservation of momentum, conservation of charge\nConservation of charge, conservation of energy"],
            ["Drift velocity of the free electrons in a conducting wire carrying a current i is v. If in a wire of the same metal, but of double the radius, the current be 2i then the drift velocity of the electrons will be\n", "v/4\nv/2\nv\n4v"],
            ["If a wire is stretched to make it double longer, its resistance will\n", "Increase by 4 times\nincrease by 2\ndecrease by 4 times\ndecrease by 2times"],
            ["In a meter bridge experiment the ratio of left gap resistance to right gap resistance is 1:3.The balance point from left is:\n", "20cm\n25cm\n30cm\n35cm"],
            ["When a metal conductor connect to left gap of a meter bridge is heated the balancing point\n", "shifts towards right\nshifts towards left\nremains unchanged\nremains to zero"],
            ["A circular coil of radius 4 cm and of 20 turns carries a current of 3 amperes. It is placed in a magnetic field of intensity of 0.5 Weber/mÂ². The magnetic dipole moment of the coil is\n", "0.15 Am2\n0.3 Am2\n0.45 Am2\n0.6 Am2"],
            ["At a certain place on earth, BH=âˆš3 BV angle of dip at this place is\n", "60Â°\n30Â°\n45Â°\n90Â°"],
            ["The angle of dip at a certain place where the horizontal and vertical components of the earthâ€™s magnetic field are equal is\n", "30Â°\n75Â°\n60Â°\n45Â°"],
            ["The angle between Magnetic meridian and the geographic meridian is known as\n", "Angle of dip\nmagnetic field inclination\nMagnetic field declination\nangle of magnetism"],
            ["Which of the following are the Elements of Earthâ€™s magnetic fields? (i) Magnetic declination (ii) Angle of dip or magnetic inclination (iii) Vertical component of earthâ€™s magnetic field (iv) Horizontal component of earthâ€™s magnetic field. Choose the correct option\n", "(i), (ii) and (iii)\n(i), (ii) and (iv)\n(ii), (iii) and (iv)\n(i), (iii) and (iv)"],
            ["Where on the surface of Earth is the vertical component of Earthâ€™ s magnetic field zero ?\n", "at north pole\nat South pole\nat Equator\nnone of these"],
            ["A small magnet is pivoted to move freely in the magnetic meridian. At what place on the surface of the earth will the magnet be vertical?\n", "at pole\nat the place where angle of dip is 450\nat Equator\nnone of these"],
            ["Which of the following are true (i) Angle of dip at equator is zero (ii) The value of Horizontal component of Earthâ€™s Magnetic Field is maximum at equator (iii) The value of Vertical component of Earthâ€™s Magnetic Field is maximum at equator (iv) The value of Horizontal component of Earthâ€™s Magnetic Field is minimum at Poles. Choose the correct option :-\n", "(i), (ii) and (iii)\n(i), (ii) and (iv)\n(ii), (iii) and (iv)\n(i), (iii) and (iv)"],
            ["An Electron in an atom revolves around the nucleus in an orbit of radius r with frequency f, the magnetic moment of electron is\n", "efÏ€r2\nefÏ€r2/2\n2efÏ€r2\nefÏ€r2/3"],
            ["At the place the horizontal component of magnetic field is B and angle of dip is 600, the value of the horizontal component of magnetic field at equator is\n", "B\nzero\n2B\nB/2"],
            ["When current in a coil change from 5 A to 2 A in 0.1 s, average voltage of 50V is produced. The self-inductance of the coil is\n", "1.67H\n6H\n3H\n0.67 H"],
            ["In a pure capacitive circuit if the frequency of ac source is doubled, then its capacitive reactance will be", "remains same\ndoubled\nhalved\nzero"]
        ],
        "sa": [
            ["An arbitrary surface encloses a dipole. What is the electric flux through this surface?", ""],
            ["A metallic spherical shell has an inner radius R1 and outer radius R2. A charge Q is placed at the centre of the spherical cavity. What will be surface charge density on (i) the inner surface, and (ii) the outer surface?", ""],
            ["The dimensions of an atom are of the order of an Angstrom. Thus there must be large electric fields between the protons and electrons. Why, then is the electrostatic field inside a conductor zero?", ""],
            ["If the total charge enclosed by a surface is zero, does it imply that the electric field everywhere on the surface is zero? Conversely, if the electric field everywhere on a surface is zero, does it imply that net charge inside is zero.", ""],
            ["Sketch the electric field lines for a uniformly charged hollow cylinder shown in Fig 1.8.", ""],
            ["What will be the total flux through the faces of the cube (Fig. 1.9) with side of length a if a charge q is placed at (a) A: a corner of the cube. (b) B: mid-point of an edge of the cube. (c) C: centre of a face of the cube. (d) D: mid-point of B and C.", ""],
            ["Consider two conducting spheres of radii R1 and R2 with R1 > R2. If the two are at the same potential, the larger sphere has more charge than the smaller sphere. State whether the charge density of the smaller sphere is more or less than that of the larger one.", ""],
            ["Do free electrons travel to a region of higher potential or lower potential?", ""],
            ["Can there be a potential difference between two adjacent conductors carrying the same charge?", ""],
            ["Can the potential function have a maximum or minimum in free space?", ""],
            ["A test charge q is made to move in the electric field of a point charge Q along two different closed paths (Fig. 2.6). First path has sections along and perpendicular to lines of the electric field. Second path is a rectangular loop of the same area as the first loop. How does the work done compare in the two cases?", ""],
            ["Is the momentum conserved when charge crosses a junction in an electric circuit? Why or why not?", ""],
            ["The relaxation time τ is nearly independent of applied E field whereas it changes significantly with temperature T. First fact is (in part) responsible for Ohm\"s law whereas the second fact leads to variation of resistivity with temperature. Elaborate why?", ""],
            ["What are the advantages of the null-point method in a Wheatstone bridge? What additional measurements would be required to calculate Runknown by any other method?", ""],
            ["What is the advantage of using thick metallic strips to join wires in a potentiometer?", ""],
            ["For wiring in the home, one uses Cu wires or Al wires. What considerations are involved in this?", ""],
            ["Why are alloys used for making standard resistance coils?", ""],
            ["Power P is to be delivered to a device via transmission cables having resistance RC. If V is the voltage across R and I the current through it, find the power wasted and how can it be reduced.", ""],
            ["AB is a potentiometer wire (Fig 3.4). If the value of R is increased, in which direction will the balance point J shift?", ""],
            ["While doing an experiment with a potentiometer (Fig 3.5), it was found that the deflection is one-sided and (i) the deflection decreased while moving from one end A of the wire to the end B; (ii) the deflection increased while the jockey was moved towards the end B. (i) Which terminal +or -ve of the cell E1, is connected at X in case (i) and how is E1 related to E? (ii) Which terminal of the cell E1 is connected at X in case (ii)?", ""],
            ["A cell of emf E and internal resistance r is connected across an external resistance R. Plot a graph showing the variation of P.D. across R, versus R.", ""],
            ["Verify that the cyclotron frequency ω = eB/m has the correct dimensions of [T]-1.", ""],
            ["Show that a force that does no work must be a velocity-dependent force.", ""],
            ["The magnetic force depends on v which depends on the inertial frame of reference. Does then the magnetic force differ from inertial frame to frame? Is it reasonable that the net acceleration has a different value in different frames of reference?", ""],
            ["Describe the motion of a charged particle in a cyclotron if the frequency of the radio frequency (rf) field were doubled.", ""],
            ["Two long wires carrying current I1 and I2 are arranged as shown in Fig. 4.1. The one carrying current I1 is along is the x-axis. The other carrying current I2 is along a line parallel to the y-axis given by x = 0 and z = d. Find the force exerted at O2 because of the wire along the x-axis.", ""],
            ["A proton has spin and magnetic moment just like an electron. Why then its effect is neglected in magnetism of materials?", ""],
            ["A permanent magnet in the shape of a thin cylinder of length 10 cm has M = 106 A/m. Calculate the magnetization current IM.", ""],
            ["Explain quantitatively the order of magnitude difference between the diamagnetic susceptibility of N2 (~5 x 10-9) (at STP) and Cu (~10-5).", ""],
            ["From a molecular viewpoint, discuss the temperature dependence of susceptibility for diamagnetism, paramagnetism, and ferromagnetism.", ""],
            ["A ball of superconducting material is dipped in liquid nitrogen and placed near a bar magnet. (i) In which direction will it move? (ii) What will be the direction of its magnetic moment?", ""],
            ["Consider a magnet surrounded by a wire with an on/off switch S (Fig 6.4). If the switch is thrown from the off position (open circuit) to the on position (closed circuit), will a current flow in the circuit? Explain.", ""],
            ["A wire in the form of a tightly wound solenoid is connected to a DC source, and carries a current. If the coil is stretched so that there are gaps between successive elements of the spiral coil, will the current increase or decrease? Explain.", ""],
            ["A solenoid is connected to a battery so that a steady current flows through it. If an iron core is inserted into the solenoid, will the current increase or decrease? Explain.", ""],
            ["Consider a metal ring kept on top of a fixed solenoid (say on cardboard) (Fig 6.5). The centre of the ring coincides with the axis of the solenoid. If the current is suddenly switched on, the metal ring jumps up. Explain.", ""],
            ["Consider a metal ring kept (supported by cardboard) on top of a fixed solenoid carrying a current I (see Fig 6.5). The centre of the ring coincides with the axis of the solenoid. If the current in the solenoid is switched off, what will happen to the ring?", ""],
            ["Consider a metallic pipe with an inner radius of 1 cm. If a cylindrical bar magnet of radius 0.8 cm is dropped through the pipe, it takes more time to come down than it takes for a similar unmagnetized cylindrical iron bar dropped through the metallic pipe. Explain.", ""],
            ["If a LC circuit is considered analogous to a harmonically oscillating spring block system, which energy of the LC circuit would be analogous to potential energy and which one analogous to kinetic energy?", ""],
            ["Draw the effective equivalent circuit of the circuit shown in Fig 7.1, at very high frequencies and find the effective impedance.", ""],
            ["Study the circuits (a) and (b) shown in Fig 7.2 and answer the following questions. Fig. 7.2 ~ R1 C1 L1 L2 R2 C2 R3 ~ R ~ RC L (a) (b) (a) Under which conditions would the rms currents in the two circuits be the same? (b) Can the rms current in circuit (b) be larger than that in (a)?", ""],
            ["Can the instantaneous power output of an ac source ever be negative? Can the average power output be negative?", ""],
            ["In a series LCR circuit, the plot of I max vs w is shown in Fig 7.3. Find the bandwidth and mark it in the figure. Fig. 7.1 .5 1.0 1.5 2.0", ""],
            ["The alternating current in a circuit is described by the graph shown in Fig 7.4. Show rms current in this graph.", ""],
            ["How does the sign of the phase angle phi, by which the supply voltage leads the current in an LCR series circuit, change as the supply frequency is gradually increased from very low to very high values.", ""],
            ["Will the focal length of a lens for red light be more, same or less than that for blue light?", ""],
            ["The near vision of an average person is 25 cm. To view an object with an angular magnification of 10, what should be the power of the microscope?", ""],
            ["An unsymmetrical double convex thin lens forms the image of a point object on its axis. Will the position of the image change if the lens is reversed?", ""],
            ["Three immiscible liquids of densities d1 > d2 > d3 and refractive indices µ1 > µ2 > µ3 are put in a beaker. The height of each liquid column is 3h. A dot is made at the bottom of the beaker. For near-normal vision, find the apparent depth of the dot.", ""],
            ["For a glass prism (µ = 3), the angle of minimum deviation is equal to the angle of the prism. Find the angle of the prism.", ""],
            ["Is Huygen\"s principle valid for longitudinal sound waves?", ""],
            ["Consider a point at the focal point of a convergent lens. Another convergent lens of short focal length is placed on the other side. What is the nature of the wavefronts emerging from the final image?", ""],
            ["What is the shape of the wavefront on Earth for sunlight?", ""],
            ["Why is the diffraction of sound waves more evident in daily experience than that of light waves?", ""],
            ["The human eye has an approximate angular resolution of phase-difference = 5.8 x 10^-5 rad, and a typical photoprinter prints a minimum of 300 dpi (dots per inch, 1 inch = 2.54 cm). At what minimal distance z should a printed page be held so that one does not see the individual dots.", ""],
            ["A polaroid (I) is placed in front of a monochromatic source. Another polaroid (II) is placed in front of this polaroid (I) and rotated till no light passes. A third polaroid (III) is now placed in between (I) and (II). In this case, will light emerge from (II)? Explain.", ""],
            ["A proton and an alpha-particle are accelerated, using the same potential difference. How are the de Broglie wavelengths p and a related to each other?", ""],
            ["(i) In the explanation of photoelectric effect, we assume one photon of frequency v collides with an electron and transfers its energy. This leads to the equation for the maximum energy Emax of the emitted electron as Emax = hv - φ0, where φ0 is the work function of the metal. If an electron absorbs 2 photons (each of frequency v), what will be the maximum energy for the emitted electron? (ii) Why is this fact (two-photon absorption) not taken into consideration in our discussion of the stopping potential?", ""],
            ["There are materials that absorb photons of shorter wavelength and emit photons of longer wavelength. Can there be stable substances that absorb photons of larger wavelength and emit light of shorter wavelength?", ""],
            ["Do all the electrons that absorb a photon come out as photoelectrons?", ""],
            ["There are two sources of light, each emitting with a power of 100 W. One emits X-rays of wavelength 1 nm, and the other emits visible light at 500 nm. Find the ratio of the number of photons of X-rays to the photons of visible light of the given wavelength.", ""],
            ["The mass of a hydrogen atom is less than the sum of the masses of a proton and electron. Why is this?", ""],
            ["Imagine removing one electron from He4 and He3. Their energy levels, as worked out on the basis of the Bohr model, will be very close. Explain why.", ""],
            ["When an electron falls from a higher energy to a lower energy level, the difference in the energies appears in the form of electromagnetic radiation. Why cannot it be emitted as other forms of energy?", ""],
            ["Would the Bohr formula for the H-atom remain unchanged if a proton had a charge (+4/3)e and an electron had a charge (-3/4)e, where e = 1.6 x 10^-19 C. Give reasons for your answer.", ""],
            ["Consider two different hydrogen atoms. The electron in each atom is in an excited state. Is it possible for the electrons to have different energies but the same orbital angular momentum according to the Bohr model?", ""],
            ["3He2 and 3He1 nuclei have the same mass number. Do they have the same binding energy?", ""],
            ["Draw a graph showing the variation of decay rate with the number of active nuclei.", ""],
            ["Which sample, A or B shown in Fig. 13.2 has a shorter mean-life?", ""],
            ["Which one of the following cannot emit radiation and why? Excited nucleus, excited electron.", ""],
            ["In pair annihilation, an electron and a positron destroy each other to produce gamma radiation. How is the momentum conserved?", ""],
            ["Why are elemental dopants for Silicon or Germanium usually chosen from group XIII or group XV?", ""],
            ["Sn, C, and Si, Ge are all group XIV elements. Yet, Sn is a conductor, C is an insulator, while Si and Ge are semiconductors. Why?", ""],
            ["Can the potential barrier across a p-n junction be measured by simply connecting a voltmeter across the junction?", ""],
            ["Draw the output waveform across the resistor (Fig.14.8).", ""],
            ["The amplifiers X, Y, and Z are connected in series. If the voltage gains of X, Y, and Z are 10, 20, and 30, respectively and the input signal is 1 mV peak value, then what is the output signal voltage (peak value) (i) if the dc supply voltage is 10V? (ii) if the dc supply voltage is 5V?", ""],
            ["In a CE transistor amplifier, there is a current and voltage gain associated with the circuit. In other words, there is a power gain. Considering power as a measure of energy, does the circuit violate conservation of energy?", ""],
            ["Which of the following would produce analog signals and which would produce digital signals? (i) A vibrating tuning fork. (ii) Musical sound due to a vibrating sitar string. (iii) Light pulse. (iv) Output of NAND gate.", ""],
            ["Would sky waves be suitable for transmission of TV signals of 60 MHz frequency?", ""],
            ["Two waves A and B of frequencies 2 MHz and 3 MHz, respectively are beamed in the same direction for communication via sky wave. Which one of these is likely to travel a longer distance in the ionosphere before suffering total internal reflection?", ""],
            ["The maximum amplitude of an A.M. wave is found to be 15 V while its minimum amplitude is found to be 3 V. What is the modulation index?", ""],
            ["Compute the LC product of a tuned amplifier circuit required to generate a carrier wave of 1 MHz for amplitude modulation.", ""],
            ["Why is an AM signal likely to be noisier than an FM signal upon transmission through a channel?", ""]
        ],
        "ma": [],
        "cb": [
            [
                "Read the para given below and answer the questions that follow:\nResonant Series LCR Circuit. When the frequency of ac supply is such that the inductive reactance and capacitive reactance become equal, the impedance of the series LCR circuit is equal to the ohmic resistance in the circuit. Such a series LCR circuit is known as resonant series LCR circuit and the frequency of the ac supply is known as resonant frequency. Resonance phenomenon is exhibited by a circuit only if both L and C are present in the circuit. We cannot have resonance in a RL or RC circuit. A series LCR circuit with L = 0.12 H, C = 480 nF, R = 23 Ω is Connect to a 230 V variable frequency supply.",
                "",
                [
                    ["Find the value of source for which current amplitude is maximum.", "mcq", "222.32 Hz\n550.52 Hz\n663.48 Hz\n770 Hz"],
                    ["The value of maximum current is", "mcq", "14.14 A\n22.52 A\n50.25 A\n47.41 A"],
                    ["The value of maximum power is", "mcq", "2200 W\n2299.3 W\n5500 W\n4700 W"],
                    ["What is the Q-factor of the given circuit?", "mcq", "25 A\n42.21 A\n35.42 A\n21.74 A"],
                    ["At resonance which of the following physical quantity is maximum?", "mcq", "Impedance\nCurrent\nBoth (a) and (b)\nNeither (a) nor (b)"]
                ]
            ],
            [
                "\nMETAL DETECTOR\nMetal detectors are useful for finding metal inclusions hidden within objects, "
                "or metal objects buried underground. They often consist of a handheld unit with a sensor probe which "
                "can be swept over the ground or other objects. Another common type are stationary “walk through” metal detectors. "
                "At an airport, a person is made to walk through the doorway of a metal detector, for security reasons. "
                "If she/he is carrying anything made of metal, the metal detector emits a sound. When you walk through a metal detector, "
                "you are, in fact, walking through a coil of many turns. The coil is connected to a capacitor tuned so that the circuit "
                "is in resonance. When you walk through with metal in your pocket, the impedance of the circuit changes – resulting in "
                "significant change in current in the circuit. This change in current is detected and the electronic circuitry causes a sound to be emitted as an alarm",
                "",
                [
                    ["How to increase the energy stored in an inductor by four times?", "mcq", "By doubling the current\nThis is not possible\nBy doubling the inductance\nBy making current 2 times"],
                    ["Consider an inductor whose linear dimensions are tripled and the total number of turns per unit length is kept constant, what happens to the self-inductance?", "mcq", "9 times\n3 times\n27 times\n13 times"],
                    ["Lenz law is based on which of the following conservation", "mcq", "Charge\nMass\nMomentum\nEnergy"],
                    ["What will be the acceleration of the falling bar magnet which passes through the ring such that the ring is held horizontally and the bar magnet is dropped along the axis of the ring?", "mcq", "It depends on the diameter of the ring and the length of the magnet\nIt is equal due to gravity\nIt is less than due to gravity"]
                ]
            ]
        ],
        "la": []
    }
}
